%% Daten (in Stunden)

ohne_offen  = [2 + 22/60, 7 + 28/60];
ohne_mittig = [3 + 55/60, 12 + 23/60];

mit_offen   = [4 + 56/60, 15 + 36/60];
mit_mittig  = [5 + 56/60, 18 + 41/60];

%% Prozentuale Verlängerung

plus_offen  = (mit_offen ./ ohne_offen - 1) * 100;
plus_mittig = (mit_mittig ./ ohne_mittig - 1) * 100;

%% X-Positionen

x = [1 2];

offset = 0.18;

figure;
hold on;
grid on;
box on;

%% Balken MIT Schalldämpfung (hinten)

bar(x - offset, mit_offen, ...
    0.35, ...
    'FaceColor', [0.7 0.7 1], ...
    'EdgeColor', 'k');

bar(x + offset, mit_mittig, ...
    0.35, ...
    'FaceColor', [1 0.7 0.7], ...
    'EdgeColor', 'k');

%% Balken OHNE Schalldämpfung (vorne)

bar(x - offset, ohne_offen, ...
    0.35, ...
    'FaceColor', [0 0.2 0.8], ...
    'EdgeColor', 'k');

bar(x + offset, ohne_mittig, ...
    0.35, ...
    'FaceColor', [0.8 0.2 0], ...
    'EdgeColor', 'k');

%% Absolute Werte auf die Balken schreiben

margin = 0.3;   % Abstand vom oberen Rand

for i = 1:2

    % --- OFFEN ---

    % Wert ohne SD
    text( ...
        x(i) - offset, ...
        ohne_offen(i) - margin, ...
        sprintf('%.2f h', ohne_offen(i)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'Color', 'w', ...
        'FontWeight', 'bold');

    % Wert mit SD
    text( ...
        x(i) - offset, ...
        mit_offen(i) - margin, ...
        sprintf('%.2f h', mit_offen(i)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'FontWeight', 'bold');

    % Prozentlabel knapp unter dem Maximum
    text( ...
        x(i) - offset, ...
        mit_offen(i) + 1.2, ...
        sprintf('+%.0f%%', plus_offen(i)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'FontWeight', 'bold');


    % --- MITTIG ---

    % Wert ohne SD
    text( ...
        x(i) + offset, ...
        ohne_mittig(i) - margin, ...
        sprintf('%.2f h', ohne_mittig(i)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'Color', 'w', ...
        'FontWeight', 'bold');

    % Wert mit SD
    text( ...
        x(i) + offset, ...
        mit_mittig(i) - margin, ...
        sprintf('%.2f h', mit_mittig(i)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'FontWeight', 'bold');

    % Prozentlabel knapp unter dem Maximum
    text( ...
        x(i) + offset, ...
        mit_mittig(i) + 1.2, ...
        sprintf('+%.0f%%', plus_mittig(i)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'FontWeight', 'bold');

end

%sprintf('%dh %02dmin',floor(ohne_offen(i)),round(60 * mod(ohne_offen(i),1)))

%% Achsen

xticks(x);
xticklabels({'80 dB(A)', '85 dB(A)'});

xlabel('Erreichter Schallpegel mit und ohne Schalldämpfung (SD)');
ylabel('Zeit bis Grenzwert [h]');

legend( ...
    'Deckel offen (mit SD)', ...
    'Deckel mittig (mit SD)', ...
    'Deckel offen (ohne SD)', ...
    'Deckel mittig (ohne SD)', ...
    'Location', 'northwest');

hold off;

%%
xticks(x);
xticklabels({'80 dB(A)', '85 dB(A)'});

xlabel('Reached Sound Level with and without the Sound Dampening (SD)');
ylabel('Time until Limit [h]');

legend( ...
    'Lid open (with SD)', ...
    'Lid half-open (with SD)', ...
    'Lid open (without SD)', ...
    'Lid half-open (without SD)', ...
    'Location', 'northwest');

hold off;